1. Preparing Past data

In [3]:
import pandas as pd
url = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
data = pd.read_csv(url)
data.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
# one-hot encoding
encoding = pd.get_dummies(data)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [11]:
features = data.columns.difference(['품종'])
X_data = data[features]
features_y = encoding.columns.difference(features)
y_data = encoding[features_y]
print(X_data.shape, y_data.shape)

(150, 4) (150, 3)


In [12]:
X_data.head()

꽃받침길이  꽃받침폭  꽃잎길이  꽃잎폭
0    1.4   0.2   5.1  3.5
1    1.4   0.2   4.9  3.0
2    1.3   0.2   4.7  3.2
3    1.5   0.2   4.6  3.1
4    1.4   0.2   5.0  3.6

In [13]:
y_data.head()

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

2. Make Structure

In [16]:
import tensorflow as tf
X = tf.keras.layers.Input([4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

3. Fit Model using Data

In [19]:
model.fit(X_data, y_data, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1558 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1558 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1557 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1557 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1552 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1552 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1551 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1554 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1551 - accuracy: 0.9667
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1546 - accuracy: 0.9667


4. Use Model

In [28]:
model.predict(X_data[0:5])

array([[9.9917787e-01, 8.2204939e-04, 4.5773465e-08],
       [9.9683577e-01, 3.1637724e-03, 4.7808720e-07],
       [9.9838519e-01, 1.6146876e-03, 1.6906704e-07],
       [9.9531305e-01, 4.6861605e-03, 7.7671774e-07],
       [9.9929249e-01, 7.0742652e-04, 3.4714464e-08]], dtype=float32)

In [30]:
print(y_data[0:5])

   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [31]:
model.predict(X_data[-5:])

array([[6.9543358e-07, 9.2890285e-02, 9.0710908e-01],
       [1.3666970e-06, 1.5572615e-01, 8.4427249e-01],
       [2.7500394e-06, 2.1651991e-01, 7.8347731e-01],
       [6.7499184e-07, 1.1365934e-01, 8.8634002e-01],
       [5.6333847e-06, 3.1986141e-01, 6.8013293e-01]], dtype=float32)

In [33]:
print(y_data[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [34]:
model.get_weights()

[array([[-4.5614953 , -0.8253626 ,  0.31575474],
        [-3.9872808 , -1.6552266 ,  2.003067  ],
        [ 0.7368041 , -0.11841968, -0.6419398 ],
        [ 3.372377  ,  1.014333  , -0.7729976 ]], dtype=float32),
 array([ 1.6340873,  1.4489986, -1.7504666], dtype=float32)]