# Boston Housing Data
1. Preparing Past data

In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv"
data = pd.read_csv(url)
features = data.columns.difference(['medv'])
X_data = data[features]
y_data = data[['medv']]
print(X_data.shape, y_data.shape)

(506, 13) (506, 1)


2. Make Structure

In [3]:
import tensorflow as tf
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [4]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


3. Fit Model using Data

In [9]:
model.fit(X_data, y_data, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 22.9448
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 23.0253
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 23.3045
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 22.5753
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 23.2512
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 23.0005
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 22.9559
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 22.9920
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 23.0056
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 22.6173


4. Use Model

In [13]:
print(model.predict(X_data[:5]))

[[31.798334]
 [25.95069 ]
 [31.771034]
 [31.322468]
 [29.677029]]


In [14]:
y_data[:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

# Iris Data
1. Preparing Past data

In [15]:
import pandas as pd
url = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
data = pd.read_csv(url)
# one-hot encoding
encoding = pd.get_dummies(data)

# divide variables
features = data.columns.difference(['품종'])
features_y = encoding.columns.difference(features)
X_data = data[features]
y_data = encoding[features_y]
print(X_data.shape, y_data.shape)

(150, 4) (150, 3)


2. Make Structure

In [18]:
X = tf.keras.layers.Input([4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [19]:
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


3. Fit Model using Data

In [24]:
model.fit(X_data, y_data, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0501 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0459 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0491 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0483 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0497 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0479 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0441 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0521 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0454 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0497 - accuracy: 0.9867


4. Use Model

In [26]:
print(model.predict(X_data[:5]))

[[9.9999988e-01 3.0870251e-09 1.3782943e-07]
 [9.9999964e-01 1.4874250e-08 3.3726769e-07]
 [9.9999964e-01 1.1989858e-08 2.9930169e-07]
 [9.9999952e-01 3.0405282e-08 4.4708321e-07]
 [9.9999988e-01 3.1263581e-09 1.3463007e-07]]


In [27]:
y_data[:5]

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

In [28]:
print(model.predict(X_data[-5:]))

[[1.5839497e-07 2.2390797e-03 9.9776077e-01]
 [5.9836015e-07 1.4210261e-02 9.8578912e-01]
 [2.2776952e-07 1.6989678e-02 9.8301011e-01]
 [6.3912630e-08 5.8771484e-04 9.9941218e-01]
 [3.8990007e-07 3.3873286e-02 9.6612632e-01]]


In [29]:
y_data[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1