Layer
  - tf.keras.layers.BatchNormalization()
  - tf.keras.layers.Activation('swish')

Data
  - Boston Housing: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv
  - Iris: https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv

# Boston Housing Data
1. Preparing Past Data

In [1]:
import pandas as pd
url = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv"
data = pd.read_csv(url)
features = data.columns.difference(['medv'])
X_data = data[features]
y_data = data[['medv']]
print(X_data.shape, y_data.shape)

(506, 13) (506, 1)


2. Make Structure

In [3]:
import tensorflow as tf
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10)(X)
H = tf.keras.layers.BatchNormalization()(H) # Use Batch Normalization
H = tf.keras.layers.Activation('swish')(H)  # Use activation Function
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [4]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                140       
_________________________________________________________________
batch_normalization (BatchNo (None, 10)                40        
_________________________________________________________________
activation_1 (Activation)    (None, 10)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 11        
Total params: 191
Trainable params: 171
Non-trainable params: 20
_________________________________________________________________


3. Fit Model using Data

In [8]:
model.fit(X_data,y_data, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 12.2782
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 12.5717
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 12.6446
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 13.2062
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 11.4155
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 12.3304
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 11.3123
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 12.6272
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 13.0388
Epoch 10/10
16/16 [==============================] - 0s 1ms/step - loss: 10.8056


4. Use Model

In [9]:
print(model.predict(X_data[:5]))

[[25.917686]
 [22.777103]
 [32.39832 ]
 [30.048037]
 [30.007936]]


In [10]:
y_data[:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

# Iris Data

1. Preparing Past Data

In [11]:
import pandas as pd
url = "https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv"
data = pd.read_csv(url)
# one-hot encoding
encoding = pd.get_dummies(data)

# divide variables
features = data.columns.difference(['품종'])
features_y = encoding.columns.difference(features)
X_data = data[features]
y_data = encoding[features_y]
print(X_data.shape, y_data.shape)

(150, 4) (150, 3)


2. Make Structure

In [14]:
X = tf.keras.layers.Input([4])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(3)(H)
H = tf.keras.layers.BatchNormalization()(H)
Y = tf.keras.layers.Activation('softmax')(H)

model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [15]:
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 40        
_________________________________________________________________
batch_normalization_5 (Batch (None, 8)                 32        
_________________________________________________________________
activation_6 (Activation)    (None, 8)                 0         
_________________________________________________________________
dense_9 (Dense)              (None, 8)                 72        
_________________________________________________________________
batch_normalization_6 (Batch (None, 8)                 32        
_________________________________________________________________
activation_7 (Activation)    (None, 8)                 0   

3. Fit Model using Data

In [17]:
model.fit(X_data, y_data, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0295 - accuracy: 0.9867
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0356 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0332 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0985 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0309 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0620 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0358 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0263 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0444 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0270 - accuracy: 0.9933


4. Use Model

In [18]:
print(model.predict(X_data[:5]))

[[9.9972600e-01 1.3596077e-04 1.3799191e-04]
 [9.9954164e-01 3.4731536e-04 1.1104275e-04]
 [9.9960834e-01 1.9890867e-04 1.9282143e-04]
 [9.9926192e-01 2.5195675e-04 4.8613985e-04]
 [9.9966669e-01 9.4388553e-05 2.3888492e-04]]


In [19]:
y_data[:5]

품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0

In [20]:
print(model.predict(X_data[-5:]))

[[1.2602724e-04 1.3044373e-04 9.9974352e-01]
 [7.9618668e-04 3.4733415e-03 9.9573046e-01]
 [5.1764387e-04 1.4238263e-02 9.8524415e-01]
 [2.7886254e-04 1.0230256e-03 9.9869812e-01]
 [6.1670388e-04 7.9500981e-02 9.1988230e-01]]


In [21]:
y_data[-5:]

품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1